import Image from "next/image";

const logos = [
  { name: "Attio", src: "/images/logo-attio.jpg" },
  { name: "La Growth Machine", src: "/images/logo-lagrowthmachine.png" },
  { name: "gojiberry", src: "/images/logo-gojiberry.png" },
  { name: "ChatSEO", src: "/images/logo-chatseo.png" },
  { name: "Abyssale", src: "/images/logo-abyssale.png" },
  { name: "BlogSEO", src: "/images/logo-blogseo.png", caseStudy: true },
  { name: "lemlist", src: "/images/logo-lemlist.png" },
  { name: "folk", src: "/images/logo-folk.png" },
  { name: "Leadbay", src: "/images/logo-leadbay.png" },
  { name: "Ringover", src: "/images/logo-ringover.png" },
];

function LogoTrack() {
  return (
    <div className="flex min-w-max items-center gap-10 px-6">
      {logos.map((logo) => (
        <div key={logo.name} className="flex shrink-0 items-center gap-2">
          <Image
            src={logo.src}
            alt={logo.name}
            width={120}
            height={32}
            className="h-7 w-auto object-contain opacity-70 grayscale"
          />
          {logo.caseStudy && (
            <a
              href="#case-study"
              className="rounded-full bg-white/90 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide text-foreground shadow-sm"
            >
              Case study →
            </a>
          )}
        </div>
      ))}
    </div>
  );
}

export default function Hero() {
  return (
    <section className="relative min-h-[100svh] overflow-hidden">
      {/* Sky / clouds background */}
      <Image
        src="/images/hero-clouds.png"
        alt=""
        fill
        priority
        className="object-cover object-center"
        sizes="100vw"
      />
      <div className="absolute inset-0 bg-gradient-to-b from-sky-200/20 via-transparent to-[#f7f6f3]/80" />

      <div className="relative z-10 mx-auto flex min-h-[100svh] max-w-5xl flex-col px-4 pb-28 pt-28 sm:px-6 sm:pt-32 lg:px-8">
        <div className="flex flex-1 flex-col items-center justify-center text-center">
          {/* Top badge */}
          <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-black/5 bg-white/90 px-3 py-1.5 shadow-sm backdrop-blur">
            <span className="flex h-5 w-5 items-center justify-center rounded-full bg-[#0A66C2] text-[10px] font-bold text-white">
              in
            </span>
            <span className="text-[15.5px] font-medium text-[#33353B]">
              Where B2B brands work with creators
            </span>
          </div>

          <h1 className="lp-h1 mx-auto max-w-[980px]">
            The B2B LinkedIn
            <br />
            Creator Marketplace.
          </h1>

          <p className="lp-lead mx-auto mt-[30px] max-w-[660px]">
            Find the creators your buyers already trust, launch campaigns in
            days, and track the clicks, leads and pipeline generated by every
            post.
          </p>

          <div className="mt-8 flex flex-col items-center gap-4 sm:flex-row">
            <a
              href="#pricing"
              className="lp-btn inline-flex items-center gap-[11px] rounded-xl bg-[#17181C] px-7 py-4 text-white transition hover:opacity-90"
            >
              Launch a campaign
              <span aria-hidden>→</span>
            </a>
            <a
              href="#how-it-works"
              className="lp-btn inline-flex items-center gap-2 text-[#17181C] transition hover:opacity-70"
            >
              See how Naano works
              <span aria-hidden>→</span>
            </a>
          </div>

          <p className="mt-10 flex items-center gap-2 text-[15.5px] font-medium text-[#555b63]">
            <span className="inline-flex h-4 w-4 items-center justify-center rounded-full border border-foreground/25 text-[9px]">
              ✓
            </span>
            Trusted by modern B2B teams
          </p>
        </div>

        {/* Logo slider behind / under the hero copy */}
        <div className="mt-8 overflow-hidden [mask-image:linear-gradient(to_right,transparent,black_8%,black_92%,transparent)]">
          <div className="logo-slider flex w-max">
            <LogoTrack />
            <LogoTrack />
          </div>
        </div>
      </div>

      {/* Bottom search bar */}
      <div className="absolute inset-x-0 bottom-6 z-20 flex justify-center px-4">
        <div className="flex w-full max-w-xl items-center gap-3 rounded-full border border-black/5 bg-white/95 px-4 py-3 shadow-[0_12px_40px_-16px_rgba(23,24,28,0.35)] backdrop-blur">
          <span className="grid h-6 w-6 place-items-center text-foreground/40">
            <svg viewBox="0 0 16 16" className="h-4 w-4 fill-current" aria-hidden>
              <circle cx="3" cy="3" r="1.5" />
              <circle cx="8" cy="3" r="1.5" />
              <circle cx="13" cy="3" r="1.5" />
              <circle cx="3" cy="8" r="1.5" />
              <circle cx="8" cy="8" r="1.5" />
              <circle cx="13" cy="8" r="1.5" />
            </svg>
          </span>
          <input
            type="text"
            readOnly
            placeholder="What would you like to see?"
            className="w-full bg-transparent text-sm text-foreground outline-none placeholder:text-foreground/40"
          />
          <span className="text-foreground/35" aria-hidden>
            ⌄
          </span>
        </div>
      </div>
    </section>
  );
}
